// @generated by scripts/codegen.py — DO NOT EDIT
// Regenerate: make codegen

// stdlib-only: Apple frameworks excluded
// Included modules: Swift, SwiftOnoneSupport, _Backtracing, _Concurrency, _Differentiation, _RegexParser, _StringProcessing, _StringProcessing_Unicode
#pragma once
#include <stdint.h>

// Type kind constants
#define MOD_STRUCT    0u
#define MOD_CLASS     1u
#define MOD_ENUM      2u
#define MOD_PROTOCOL  3u
#define MOD_TYPEALIAS 4u
#define MOD_ACTOR     5u

typedef struct { const char *name; uint8_t kind; } ModuleTypeEntry;
typedef struct {
  const char          *module;
  const ModuleTypeEntry *types;
  uint32_t              count;
} ModuleStub;

#define MODULE_STUB_COUNT 3u
extern const ModuleStub MODULE_STUBS[MODULE_STUB_COUNT];

const ModuleStub *module_stub_find(const char *module_name);
