/**
 * @file char_tables.h
 * @brief C11 lexer lookup tables — character classification, keyword hash,
 *        and scanner function declarations.
 *
 * @generated by scripts/codegen.py tables — DO NOT EDIT
 * Source: SwiftSyntax (Swift 1.127.15) + include/token.h
 *
 * Tables:
 *   LEX_CHAR_CLASS[256]  — byte → character class (CC_WHITESPACE, CC_DIGIT, ...)
 *   LEX_CHAR_TOKEN[256]  — byte → token type (TT_IDENTIFIER, TT_OPERATOR, ...)
 *   LEX_ACTION[10]       — character class → scan action (0-4)
 *   LEX_KW_ID/LEN/FIRST/STR — FNV-1a keyword hash table (2-probe)
 */
#ifndef CHAR_TABLES_H
#define CHAR_TABLES_H

#include "unicode_ranges.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Character Classes — LEX_CHAR_CLASS[byte] result values                │
 * └──────────────────────────────────────────────────────────────────────────┘ */

#define CC_NULL        0   /**< NUL byte                       */
#define CC_WHITESPACE  1   /**< space, tab                     */
#define CC_NEWLINE     2   /**< LF, CR                         */
#define CC_DIGIT       3   /**< 0-9                            */
#define CC_UPPER       4   /**< A-Z                            */
#define CC_LOWER       5   /**< a-z, _                         */
#define CC_UNICODE     6   /**< bytes >= 0x80 (non-ASCII)      */
#define CC_STRING      7   /**< " or '                         */
#define CC_DOLLAR      8   /**< $                              */
#define CC_SYMBOL      9   /**< all other printable ASCII      */

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Token Types — LEX_CHAR_TOKEN[byte] result values                      │
 * └──────────────────────────────────────────────────────────────────────────┘ */

#define TT_IDENTIFIER         10   /**< letter, _, $, Unicode         */
#define TT_INTEGER_LITERAL    11   /**< digit                         */
#define TT_FLOAT_LITERAL      12   /**< digit with fraction/exponent  */
#define TT_STRING_LITERAL     13   /**< " or '                        */
#define TT_OPERATOR           15   /**< operator characters           */
#define TT_PUNCT              16   /**< ()[]{},:;                     */
#define TT_WHITESPACE         19   /**< space, tab                    */
#define TT_NEWLINE            20   /**< LF, CR                        */
#define TT_UNKNOWN            255  /**< non-ASCII, control chars      */

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  LEX_CHAR_CLASS — 256-byte table: byte → character class               │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint8_t LEX_CHAR_CLASS[256] = {
    0, 9, 9, 9, 9, 9, 9, 9, 9, 1, 2, 9, 9, 2, 9, 9, // 0-15
    9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, // 16-31
    1, 9, 7, 9, 8, 9, 9, 7, 9, 9, 9, 9, 9, 9, 9, 9, // 32-47
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, // 48-63
    9, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, // 64-79
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 9, 9, 9, 9, 5, // 80-95
    9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, // 96-111
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 9, 9, 9, 9, 9, // 112-127
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 128-143
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 144-159
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 160-175
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 176-191
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 192-207
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 208-223
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 224-239
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 240-255
};

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  LEX_CHAR_TOKEN — 256-byte table: byte → token type                    │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint8_t LEX_CHAR_TOKEN[256] = {
    15, 15, 15, 15, 15, 15, 15, 15, 15, 19, 20, 15, 15, 20, 15, 15, // 0-15
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, // 16-31
    19, 15, 13, 15, 10, 15, 15, 13, 16, 16, 15, 15, 16, 15, 15, 15, // 32-47
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 16, 16, 15, 15, 15, 15, // 48-63
    15, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, // 64-79
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 16, 16, 16, 15, 10, // 80-95
    15, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, // 96-111
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 16, 15, 16, 15, 15, // 112-127
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 128-143
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 144-159
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 160-175
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 176-191
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 192-207
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 208-223
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 224-239
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, // 240-255
};

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  LEX_ACTION — character class → scan action                            │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 *  0 = whitespace (consume run)     3 = string (scan_string)
 *  1 = identifier (scan_ident)      4 = symbol (scan_symbol)
 *  2 = number     (scan_number)
 */

static const uint8_t LEX_ACTION[10] = {
    0, 0, 0, 2, 1, 1, 1, 3, 1, 4,
};

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Keyword Table — sorted alphabetically, binary search (O(log 67) = 6)  │
 * └──────────────────────────────────────────────────────────────────────────┘ */

typedef struct {
  const char *text;
  uint8_t     id;
} KeywordEntry;

#define LEX_KEYWORD_COUNT 67

static const KeywordEntry LEX_KEYWORDS[LEX_KEYWORD_COUNT] = {
  {"actor",            13},
  {"any",              41},
  {"as",               32},
  {"async",            53},
  {"await",            31},
  {"borrowing",        66},
  {"break",            23},
  {"case",             21},
  {"catch",            57},
  {"class",             4},
  {"consume",          64},
  {"consuming",        67},
  {"continue",         24},
  {"default",          22},
  {"defer",            28},
  {"deinit",           12},
  {"discard",          65},
  {"do",               27},
  {"else",             16},
  {"enum",              6},
  {"extension",         8},
  {"fallthrough",      25},
  {"false",            36},
  {"fileprivate",      45},
  {"final",            49},
  {"for",              17},
  {"func",              1},
  {"guard",            19},
  {"if",               15},
  {"import",            9},
  {"in",               34},
  {"infix",            62},
  {"init",             11},
  {"internal",         44},
  {"is",               33},
  {"lazy",             51},
  {"let",               3},
  {"mutating",         52},
  {"nil",              37},
  {"open",             46},
  {"operator",         63},
  {"override",         50},
  {"package",          47},
  {"postfix",          61},
  {"precedencegroup",  59},
  {"prefix",           60},
  {"private",          43},
  {"protocol",          7},
  {"public",           42},
  {"repeat",           29},
  {"rethrows",         55},
  {"return",           14},
  {"self",             38},
  {"some",             40},
  {"static",           48},
  {"struct",            5},
  {"subscript",        58},
  {"super",            39},
  {"switch",           20},
  {"throw",            26},
  {"throws",           54},
  {"true",             35},
  {"try",              30},
  {"typealias",        10},
  {"var",               2},
  {"where",            56},
  {"while",            18},
};

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  SCANNER FUNCTIONS (implemented in scan/fast.c)                        │
 * └──────────────────────────────────────────────────────────────────────────┘ */

/** @brief Binary-search keyword lookup — returns KW_* id or 0 if not a keyword. */
uint32_t keyword_detect(const uint8_t *str, uint32_t len);

/** @brief Scans an identifier (ASCII SWAR + Unicode fallback) + keyword detect. */
uint32_t scan_ident(const uint8_t *src, uint32_t pos,
                    uint32_t len, uint32_t *kw_id);

/** @brief Scans a numeric literal (dec/hex/oct/bin, fraction, exponent). */
uint32_t scan_number(const uint8_t *src, uint32_t pos,
                     uint32_t len, uint32_t *ttype);

/** @brief Scans a string literal body (memchr-based, SIMD-accelerated). */
uint32_t scan_string_body(const uint8_t *src, uint32_t pos,
                          uint32_t len, uint32_t *lines);

#endif /* CHAR_TABLES_H */
