/**
 * @file unicode_ranges.h
 * @brief Unicode range tables for Swift identifier and operator classification.
 *
 * @generated by scripts/gen_unicode_tables.py — DO NOT EDIT
 *
 * Source: The Swift Programming Language (6.2.3) — Lexical Structure
 * https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure
 *
 * Tables:
 *   UNICODE_IDENT_HEAD_RANGES        — 46 ranges (identifier-head, non-ASCII)
 *   UNICODE_IDENT_CONTINUE_RANGES    — 42 ranges (identifier-character, non-ASCII)
 *   UNICODE_OPERATOR_HEAD_RANGES     — 22 ranges (operator-head, non-ASCII)
 *   UNICODE_OPERATOR_CONTINUE_RANGES — 28 ranges (operator-character, non-ASCII)
 *
 * ASCII ranges (A-Z, a-z, _, 0-9, operator chars) are handled directly
 * in the lexer.  These tables are ONLY for non-ASCII (codepoint >= 0x80)
 * Unicode lookups.
 */
#ifndef UNICODE_RANGES_H
#define UNICODE_RANGES_H

#include <stdint.h>

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Binary Search — O(log n) range lookup                                 │
 * └──────────────────────────────────────────────────────────────────────────┘ */

/** @brief Returns 1 if codepoint falls within any of the given ranges. */
static inline int unicode_in_ranges(uint32_t cp, const uint32_t ranges[][2],
                                       uint32_t count) {
  uint32_t lo = 0, hi = count;
  while (lo < hi) {
    uint32_t mid = lo + (hi - lo) / 2;
    if (cp < ranges[mid][0])
      hi = mid;
    else if (cp > ranges[mid][1])
      lo = mid + 1;
    else
      return 1;
  }
  return 0;
}

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Identifier — head (non-ASCII)                                         │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint32_t UNICODE_IDENT_HEAD_RANGES[][2] = {
  {0x000A8, 0x000A8},  /* U+00A8 */
  {0x000AA, 0x000AA},  /* U+00AA */
  {0x000AD, 0x000AD},  /* U+00AD */
  {0x000AF, 0x000AF},  /* U+00AF */
  {0x000B2, 0x000B5},  /* U+00B2-U+00B5 */
  {0x000B7, 0x000BA},  /* U+00B7-U+00BA */
  {0x000BC, 0x000BE},  /* U+00BC-U+00BE */
  {0x000C0, 0x000D6},  /* U+00C0-U+00D6 */
  {0x000D8, 0x000F6},  /* U+00D8-U+00F6 */
  {0x000F8, 0x002FF},  /* U+00F8-U+02FF */
  {0x00370, 0x0167F},  /* U+0370-U+167F */
  {0x01681, 0x0180D},  /* U+1681-U+180D */
  {0x0180F, 0x01DBF},  /* U+180F-U+1DBF */
  {0x01E00, 0x01FFF},  /* U+1E00-U+1FFF */
  {0x0200B, 0x0200D},  /* U+200B-U+200D */
  {0x0202A, 0x0202E},  /* U+202A-U+202E */
  {0x0203F, 0x02040},  /* U+203F-U+2040 */
  {0x02054, 0x02054},  /* U+2054 */
  {0x02060, 0x020CF},  /* U+2060-U+20CF */
  {0x02100, 0x0218F},  /* U+2100-U+218F */
  {0x02460, 0x024FF},  /* U+2460-U+24FF */
  {0x02776, 0x02793},  /* U+2776-U+2793 */
  {0x02C00, 0x02DFF},  /* U+2C00-U+2DFF */
  {0x02E80, 0x02FFF},  /* U+2E80-U+2FFF */
  {0x03004, 0x03007},  /* U+3004-U+3007 */
  {0x03021, 0x0302F},  /* U+3021-U+302F */
  {0x03031, 0x0D7FF},  /* U+3031-U+D7FF */
  {0x0F900, 0x0FD3D},  /* U+F900-U+FD3D */
  {0x0FD40, 0x0FDCF},  /* U+FD40-U+FDCF */
  {0x0FDF0, 0x0FE1F},  /* U+FDF0-U+FE1F */
  {0x0FE30, 0x0FE44},  /* U+FE30-U+FE44 */
  {0x0FE47, 0x0FFFD},  /* U+FE47-U+FFFD */
  {0x10000, 0x1FFFD},  /* U+10000-U+1FFFD */
  {0x20000, 0x2FFFD},  /* U+20000-U+2FFFD */
  {0x30000, 0x3FFFD},  /* U+30000-U+3FFFD */
  {0x40000, 0x4FFFD},  /* U+40000-U+4FFFD */
  {0x50000, 0x5FFFD},  /* U+50000-U+5FFFD */
  {0x60000, 0x6FFFD},  /* U+60000-U+6FFFD */
  {0x70000, 0x7FFFD},  /* U+70000-U+7FFFD */
  {0x80000, 0x8FFFD},  /* U+80000-U+8FFFD */
  {0x90000, 0x9FFFD},  /* U+90000-U+9FFFD */
  {0xA0000, 0xAFFFD},  /* U+A0000-U+AFFFD */
  {0xB0000, 0xBFFFD},  /* U+B0000-U+BFFFD */
  {0xC0000, 0xCFFFD},  /* U+C0000-U+CFFFD */
  {0xD0000, 0xDFFFD},  /* U+D0000-U+DFFFD */
  {0xE0000, 0xEFFFD},  /* U+E0000-U+EFFFD */
};
#define UNICODE_IDENT_HEAD_RANGES_COUNT \
  (sizeof(UNICODE_IDENT_HEAD_RANGES) / sizeof(UNICODE_IDENT_HEAD_RANGES[0]))

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Identifier — continue (non-ASCII, = head + combining marks)           │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint32_t UNICODE_IDENT_CONTINUE_RANGES[][2] = {
  {0x000A8, 0x000A8},  /* U+00A8 */
  {0x000AA, 0x000AA},  /* U+00AA */
  {0x000AD, 0x000AD},  /* U+00AD */
  {0x000AF, 0x000AF},  /* U+00AF */
  {0x000B2, 0x000B5},  /* U+00B2-U+00B5 */
  {0x000B7, 0x000BA},  /* U+00B7-U+00BA */
  {0x000BC, 0x000BE},  /* U+00BC-U+00BE */
  {0x000C0, 0x000D6},  /* U+00C0-U+00D6 */
  {0x000D8, 0x000F6},  /* U+00D8-U+00F6 */
  {0x000F8, 0x0167F},  /* U+00F8-U+167F */
  {0x01681, 0x0180D},  /* U+1681-U+180D */
  {0x0180F, 0x01FFF},  /* U+180F-U+1FFF */
  {0x0200B, 0x0200D},  /* U+200B-U+200D */
  {0x0202A, 0x0202E},  /* U+202A-U+202E */
  {0x0203F, 0x02040},  /* U+203F-U+2040 */
  {0x02054, 0x02054},  /* U+2054 */
  {0x02060, 0x0218F},  /* U+2060-U+218F */
  {0x02460, 0x024FF},  /* U+2460-U+24FF */
  {0x02776, 0x02793},  /* U+2776-U+2793 */
  {0x02C00, 0x02DFF},  /* U+2C00-U+2DFF */
  {0x02E80, 0x02FFF},  /* U+2E80-U+2FFF */
  {0x03004, 0x03007},  /* U+3004-U+3007 */
  {0x03021, 0x0302F},  /* U+3021-U+302F */
  {0x03031, 0x0D7FF},  /* U+3031-U+D7FF */
  {0x0F900, 0x0FD3D},  /* U+F900-U+FD3D */
  {0x0FD40, 0x0FDCF},  /* U+FD40-U+FDCF */
  {0x0FDF0, 0x0FE44},  /* U+FDF0-U+FE44 */
  {0x0FE47, 0x0FFFD},  /* U+FE47-U+FFFD */
  {0x10000, 0x1FFFD},  /* U+10000-U+1FFFD */
  {0x20000, 0x2FFFD},  /* U+20000-U+2FFFD */
  {0x30000, 0x3FFFD},  /* U+30000-U+3FFFD */
  {0x40000, 0x4FFFD},  /* U+40000-U+4FFFD */
  {0x50000, 0x5FFFD},  /* U+50000-U+5FFFD */
  {0x60000, 0x6FFFD},  /* U+60000-U+6FFFD */
  {0x70000, 0x7FFFD},  /* U+70000-U+7FFFD */
  {0x80000, 0x8FFFD},  /* U+80000-U+8FFFD */
  {0x90000, 0x9FFFD},  /* U+90000-U+9FFFD */
  {0xA0000, 0xAFFFD},  /* U+A0000-U+AFFFD */
  {0xB0000, 0xBFFFD},  /* U+B0000-U+BFFFD */
  {0xC0000, 0xCFFFD},  /* U+C0000-U+CFFFD */
  {0xD0000, 0xDFFFD},  /* U+D0000-U+DFFFD */
  {0xE0000, 0xEFFFD},  /* U+E0000-U+EFFFD */
};
#define UNICODE_IDENT_CONTINUE_RANGES_COUNT \
  (sizeof(UNICODE_IDENT_CONTINUE_RANGES) / sizeof(UNICODE_IDENT_CONTINUE_RANGES[0]))

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Operator — head (non-ASCII)                                           │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint32_t UNICODE_OPERATOR_HEAD_RANGES[][2] = {
  {0x000A1, 0x000A7},  /* U+00A1-U+00A7 */
  {0x000A9, 0x000A9},  /* U+00A9 */
  {0x000AB, 0x000AC},  /* U+00AB-U+00AC */
  {0x000AE, 0x000AE},  /* U+00AE */
  {0x000B0, 0x000B1},  /* U+00B0-U+00B1 */
  {0x000B6, 0x000B6},  /* U+00B6 */
  {0x000BB, 0x000BB},  /* U+00BB */
  {0x000BF, 0x000BF},  /* U+00BF */
  {0x000D7, 0x000D7},  /* U+00D7 */
  {0x000F7, 0x000F7},  /* U+00F7 */
  {0x02016, 0x02017},  /* U+2016-U+2017 */
  {0x02020, 0x02027},  /* U+2020-U+2027 */
  {0x02030, 0x0203E},  /* U+2030-U+203E */
  {0x02041, 0x02053},  /* U+2041-U+2053 */
  {0x02055, 0x0205E},  /* U+2055-U+205E */
  {0x02190, 0x023FF},  /* U+2190-U+23FF */
  {0x02500, 0x02775},  /* U+2500-U+2775 */
  {0x02794, 0x02BFF},  /* U+2794-U+2BFF */
  {0x02E00, 0x02E7F},  /* U+2E00-U+2E7F */
  {0x03001, 0x03003},  /* U+3001-U+3003 */
  {0x03008, 0x03020},  /* U+3008-U+3020 */
  {0x03030, 0x03030},  /* U+3030 */
};
#define UNICODE_OPERATOR_HEAD_RANGES_COUNT \
  (sizeof(UNICODE_OPERATOR_HEAD_RANGES) / sizeof(UNICODE_OPERATOR_HEAD_RANGES[0]))

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Operator — continue (non-ASCII, = head + combining marks)             │
 * └──────────────────────────────────────────────────────────────────────────┘ */

static const uint32_t UNICODE_OPERATOR_CONTINUE_RANGES[][2] = {
  {0x000A1, 0x000A7},  /* U+00A1-U+00A7 */
  {0x000A9, 0x000A9},  /* U+00A9 */
  {0x000AB, 0x000AC},  /* U+00AB-U+00AC */
  {0x000AE, 0x000AE},  /* U+00AE */
  {0x000B0, 0x000B1},  /* U+00B0-U+00B1 */
  {0x000B6, 0x000B6},  /* U+00B6 */
  {0x000BB, 0x000BB},  /* U+00BB */
  {0x000BF, 0x000BF},  /* U+00BF */
  {0x000D7, 0x000D7},  /* U+00D7 */
  {0x000F7, 0x000F7},  /* U+00F7 */
  {0x00300, 0x0036F},  /* U+0300-U+036F */
  {0x01DC0, 0x01DFF},  /* U+1DC0-U+1DFF */
  {0x02016, 0x02017},  /* U+2016-U+2017 */
  {0x02020, 0x02027},  /* U+2020-U+2027 */
  {0x02030, 0x0203E},  /* U+2030-U+203E */
  {0x02041, 0x02053},  /* U+2041-U+2053 */
  {0x02055, 0x0205E},  /* U+2055-U+205E */
  {0x020D0, 0x020FF},  /* U+20D0-U+20FF */
  {0x02190, 0x023FF},  /* U+2190-U+23FF */
  {0x02500, 0x02775},  /* U+2500-U+2775 */
  {0x02794, 0x02BFF},  /* U+2794-U+2BFF */
  {0x02E00, 0x02E7F},  /* U+2E00-U+2E7F */
  {0x03001, 0x03003},  /* U+3001-U+3003 */
  {0x03008, 0x03020},  /* U+3008-U+3020 */
  {0x03030, 0x03030},  /* U+3030 */
  {0x0FE00, 0x0FE0F},  /* U+FE00-U+FE0F */
  {0x0FE20, 0x0FE2F},  /* U+FE20-U+FE2F */
  {0xE0100, 0xE01EF},  /* U+E0100-U+E01EF */
};
#define UNICODE_OPERATOR_CONTINUE_RANGES_COUNT \
  (sizeof(UNICODE_OPERATOR_CONTINUE_RANGES) / sizeof(UNICODE_OPERATOR_CONTINUE_RANGES[0]))

/* ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Public API                                                            │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * All functions expect a decoded Unicode codepoint (uint32_t), NOT raw
 * UTF-8 bytes.  ASCII fast-paths should be checked BEFORE calling these.
 */

/** @brief Returns 1 if cp is a valid identifier-head codepoint. */
static inline int unicode_is_ident_head(uint32_t cp) {
  return unicode_in_ranges(cp, UNICODE_IDENT_HEAD_RANGES,
                              UNICODE_IDENT_HEAD_RANGES_COUNT);
}

/** @brief Returns 1 if cp is a valid identifier-continue codepoint. */
static inline int unicode_is_ident_continue(uint32_t cp) {
  return unicode_in_ranges(cp, UNICODE_IDENT_CONTINUE_RANGES,
                              UNICODE_IDENT_CONTINUE_RANGES_COUNT);
}

/** @brief Returns 1 if cp is a valid operator-head codepoint. */
static inline int unicode_is_operator_head(uint32_t cp) {
  return unicode_in_ranges(cp, UNICODE_OPERATOR_HEAD_RANGES,
                              UNICODE_OPERATOR_HEAD_RANGES_COUNT);
}

/** @brief Returns 1 if cp is a valid operator-continue codepoint. */
static inline int unicode_is_operator_continue(uint32_t cp) {
  return unicode_in_ranges(cp, UNICODE_OPERATOR_CONTINUE_RANGES,
                              UNICODE_OPERATOR_CONTINUE_RANGES_COUNT);
}

#endif /* UNICODE_RANGES_H */
